name: "CI"
on: ["push", "pull_request"]

jobs:
  ci:
    name: "Run CI"
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macOS-latest"]
        go: ["1.16.x", "1.17.x"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: ${{ matrix.go }}
      - run: "go vet ./..."
      - run: "go test ./... -race -coverprofile=coverage.txt -covermode=atomic"
      - uses: dominikh/staticcheck-action@v1.1.0
        with:
          version: "2021.1.1"
          install-go: false
          cache-key: ${{ matrix.go }}
      - name: Upload coverage report
        uses: codecov/codecov-action@v1.0.2
        with:
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella
